config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  resource :main, only: [:index]

  get "photo" => "photos#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index

  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luke McComb | Software Developer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/main/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <a class="text_color-light text-center">
        <h1>LUKE McCOMB</h1>
      </a>
      <%= link_to 'Photography', photo_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <div class="logo-wrap">
        <svg version="1.1"
              id="Layer_1"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              x="0px"
              y="0px"
              viewBox="0 0 122 126.5"
              enable-background="new 0 0 122 126.5"
              xml:space="preserve">
          <path id="square"
                fill="none"
                stroke="#FFFFFF"
                stroke-width="5"
                stroke-miterlimit="10"
                d="M101.5,106c2.1,0,16.1,0,18,0c0,2.8,0,15.7,0,18c0,0-16.8,0-18,0C101.5,123.1,101.5,106,101.5,106z"/>
          <path id="LOGO_4_"
                fill="none"
                stroke="#FFFFFF"
                stroke-width="5"
                d="M2.5,2.5c0,22.4,0,120.8,0,121.5c0,0,91.7,0,92.2,0c0,0,0-17.4,0-18c-10,0-66.8,0-74.3,0c0-7.5,0-73.8,0-85.5c1.1,2.7,26.1,71.7,27.1,74.3c0,0,19.5,0,27,0c2.3-6.6,24.7-68.4,27-74.2c0,0,0,77.5,0,78.8c0,0,17.2,0,18,0c0,0,0-94.6,0-96.8c0,0-29.8,0-31.5,0c0,0-26.7,73.5-27,74.3c0,0-25.4-69.7-27-74.3L2.5,2.5z"/>
        </svg>
      </div>
  </div>
</div>

app/views/photos/index.html.erb
<h1>Photography</h1>

app/views/resume/index.html.erb
<div class="wrapper">
  <div class="left-panel">
    <h1>Luke McComb</h1>
    <h2>Software Developer</h2>
    <div class="links">
      <p>
        <a href="mailto:lucasmccomb@gmail.com" target="_blank">Gmail</a>
      </p>
      <p>
        <a href="tel:860-558-2003">860.558.2003</a>
      </p>
      <p>
        <a href="https://github.com/lukemccomb">GitHub</a>
      </p>
      <p>
        <a href="https://twitter.com/lukemccomb">Twitter</a>
      </p>
      <p>
        <a href="https://www.linkedin.com/in/lukemccomb">LinkedIn</a>
      </p>
    </div>
    <%= image_tag "lg1Lessbright.png" %>
  </div>
  <div class="right-panel">
    <h2>Skills</h2>
    <p>
      JavaScript, ES6, jQuery, AJAX, Backbone.js, React.js, Meteor.js, AngularJS, CoffeeScript, Node.js, Ruby, Ruby on Rails, Sinatra, ActiveRecord, HTML5, CSS3/SCSS/LESS, Git, Cloud Foundry, Heroku, AWS, Semantic UI, Bootstrap, Zurb Foundation, Postgres, MongoDB, JIRA, Pivotal Tracker, Photoshop, Illustrator
    </p>
    <h2>Experience</h2>
    <p>
      <span class="mondo">IBM</span> - <span class="position">Software Developer</span>
      <br />
      <span class="loc-date">Remote // November ’15-Present</span>
      <br />
      <h3>ETA</h3>
      <ul>
        <li>Improved and maintained existing Meteor.js application used internally by IBMers to track ongoing client engagements and view statistics related to that data</li>
        <li>Refactored all of front end markup to use Bootstrap best practices as well as changing any custom styling to modular CSS.</li>
        <li>Translated desktop size styling to tablet & mobile versions</li>
        <li>Technologies: Meteor.js, Bootstrap, LESS, MongoDB, DataTable?, d3.js, IBM Bluemix</li>
      </ul>

      <h3>ETA2</h3>
      <ul>
        <li>Helped to architect redesign of existing ETA Meteor.js into a multitennant application using Node.js/React.js/Redux/ES6</li>
        <li>Rapidly developed front end using React.js and Semantic UI while co-developer developed backend API</li>
        <li>Translated desktop size styling to tablet & mobile versions</li>
        <li>Technologies: React.js, Redux, Node.js, Webpack, ES6, SemanticUI, MongoDB, Cloud Foundry</li>
      </ul>
    </p>
    <p>
      <span class="mondo">Mondo Robot LLC</span> - <span class="position">Junior Developer</span>
      <br />
      <span class="loc-date">Boulder, CO // April ’15 - November '15</span>
      <br />
      <h3><a href="http://www.digitalglobe.com" target="_blank">DigitalGlobe</a></h3>
      <ul>
        <li>Developed in-depth company profile site detailing all products offered, serviceable industries, corportate team profiles, events, user case studies, and image gallery</li>
        <li>Developed CMS to allow client to manage page layout and styling as well as content</li>
        <li>Ruby on Rails, jQuery UI, ActiveAdmin, Zurb Foundation, SASS, Postgres, responsive/cross-device</li>
        <li>Gems: <a href="https://github.com/mbleigh/seed-fu">seed-fu</a>, <a href="https://github.com/globalize/globalize">globalize</a>, <a href="http://activeadmin.info/docs/documentation.html">ActiveAdmin</a></li>
      </ul>
    </p>

    <p>
      <span class="mondo">Mondo Robot LLC</span> - <span class="position">Developer Apprentice</span>
      <br />
      <span class="loc-date">Boulder, CO // December ’14 - March ’15</span>
      <br />
      <h3><a href="http://www.mondorobot.com" target="_blank">Mondo Robot Portfolio</a></h3>
      <ul>
        <li>Rebuilt Mondo Robot's portfolio website using Middleman and AngularJS</li>
        <li>Implemented multiple iterations of cutting-edge design features to achieve the vision of the design team</li>
        <li>Built out dual-layer main navigation</li>
        <li>Participated in creative conceptualizing with design team</li>
        <li>Middleman, AngularJS, CoffeeScript, Slimlang, Zurb Foundation, SASS, responsive/cross-device</li>
      </ul>
    </p>
    <p>
      <span class="ol">Outdoor Life Magazine</span> - <span class="position">Contract Photographer</span>
      <br />
      <span class="loc-date">Locational // Aug ’08 - May ’13</span>
      <br />
      <ul>
        <li>Photographed <a href="http://eyeofthehunt.com/" target="_blank">four hunting excursions</a>, two of which have been published</li>
        <li>Gained art direction skills in challenging wilderness environments</li>
        <li>Collaborated with multiple editors to produce quality images for editorials</li>
      </ul>
    </p>
    <h2>Education</h2>
    <p>
      <span class="gschool">Galvanize gSchool</span> - Full Stack Immersive
      <br>
      <span class="loc-date">Denver, CO // June '14 - Nov '14</span>
    </p>
    <ul>
      <li>Emphasis - Software Development</li>
      <li>Graduation Certificate - November 2014</li>
      <li>Curriculum: Ruby, Ruby on Rails, Sinatra, JavaScript, jQuery,  SCSS/CSS3, HTML5, Databases, APIs, Version Control, Agile, Test-Driven Development</li>
    </ul>
    <p>
      <span class="gschool">Syracuse University</span>
      <br>
      <span class="loc-date">Syracuse, NY // August '06 - May '10</span>
    </p>
    <ul>
      <li>S. I. Newhouse School of Public Communications</li>
      <li>Emphasis: Photography & Graphic Design</li>
      <li>B.A. Visual & Interactive Communications - May 2010</li>
    </ul>
    <h2>Projects</h2>
    <h3><a href="http://lukefolio.herokuapp.com/" target="_blank">Lukefolio</a></h3>
    <ul>
      <li>Searchable database of my Flickr images</li>
      <li>Ruby on Rails application, CSS3/SCSS, HTML5, Bourbon, JavaScript, Flickr API, Postgress Database, ActiveRecord</li>
      <li>CRUD Features: commenting, favoriting, users</li>
    </ul>
    <h3><a href="http://luke-rantly.herokuapp.com/" target="_blank">Rantly</a></h3>
    <ul>
      <li>Twitter-like social media application where users can post ‘Rants’, follow one another, comment on and favorite posts.</li>
      <li>Github: <a href="https://github.com/lukemccomb/rantly" target="_blank">https://github.com/lukemccomb/rantly</a></li>
    </ul>
  </div>
</div>